"$schema" = 'https://starship.rs/config-schema.json'

# A minimal left prompt
right_format = """
{\
$shell\
$os\
$netns\
$container\
$status\
$jobs\
$line_break\
$sudo\
$custom\
$env_var\
$direnv\
$meson\
$nix_shell\
$git_status\
$git_state\
$git_commit\
$git_branch\
$localip\
$time\
"""

[character]
success_symbol = "[}](magenta)"
error_symbol = "[}](orange)"

# move the rest of the prompt to the right
format = """
$username\
$hostname\
$directory
[}](bold purple) 
"""

[cmd_duration]
disabled = true

[time]
format = '[$time]($style)}'
time_format = "%R"

[direnv]
symbol = " "

[directory]
read_only = " 󰌾"
format = ', [$path]($style)[$read_only]($read_only_style)}:'

[git_branch]
symbol = " "
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_commit]
tag_symbol = '  '
format = '[\($hash$tag\)]($style), '

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\), '

[git_status]
format = '([$all_status$ahead_behind](bold), )'
renamed = '[R](blue)'
deleted = '[D](red)'
modified = '[*](yellow)'
stashed = '[\$](orange)'
ahead = ', [](yellow)'
behind = ', [](orange)'
conflicted = ', [](red)'
diverged = ', [](magenta)'
untracked = '[+](green)'

[hostname]
format = '[$hostname](blue)'

[nix_shell]
symbol = "  "
format = '[$symbol$name]($style), '
pure_msg = ''
impure_msg = ''

[status]
symbol = " "

[sudo]
symbol = " "

[username]
format = '{[$user]($style)@'
