"$schema" = 'https://starship.rs/config-schema.json'

# A minimal left prompt
right_format = """
{\
$cmd_duration\
$time\
}\
"""

# move the rest of the prompt to the right
format = """
{\
$username\
$sudo\
$hostname\
$directory\
} {\
$c\
$cpp\
$dart\
$fortran\
$gleam\
$golang\
$haskell\
$java\
$julia\
$kotlin\
$lua\
$nodejs\
$ocaml\
$odin\
$perl\
$php\
$python\
$ruby\
$rust\
$scala\
$swift\
$zig\
$nix_shell\
$git_status\
$git_state\
$git_commit\
$git_branch\
}:
[}](bold purple) 
"""

[character]
success_symbol = "[}](magenta)"
error_symbol = "[}](orange)"

[cmd_duration]
disabled = false
format = '[$duration]($style), '
style = 'red'

[time]
format = '[$time]($style)'
time_format = "%R"
style = 'yellow'
disabled = false

[direnv]
symbol = " "

[directory]
read_only = " 󰌾"
format = ', [$path](blue)[$read_only](yellow bold)'

[git_branch]
symbol = " "
format = '[$symbol](bold purple)[$branch(:$remote_branch)](purple)'

[git_commit]
tag_symbol = '  '
format = '[\($hash$tag\)]($style), '

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\), '

[git_status]
format = '([$all_status$ahead_behind](bold), )'
renamed = '[R](blue)'
deleted = '[D](red)'
modified = '[*](yellow)'
stashed = '[\$](orange)'
ahead = ', [](yellow)'
behind = ', [](orange)'
conflicted = ', [](red)'
diverged = ', [](magenta)'
untracked = '[N](green)'

[hostname]
format = '[$hostname](blue)'

[nix_shell]
symbol = " "
format = '[$symbol]($style), '
pure_msg = ''
impure_msg = ''

[sudo]
symbol = " "
format = ':[$symbol]($style)'

[username]
format = '[$user]($style)@'

[bun]
symbol = " "
format = '[$symbol]($style), '

[c]
symbol = " "
format = '[$symbol]($style), '

[cpp]
symbol = " "
format = '[$symbol]($style), '

[cmake]
symbol = " "
format = '[$symbol]($style), '

[crystal]
symbol = " "
format = '[$symbol]($style), '

[dart]
symbol = " "
format = '[$symbol]($style), '

[deno]
symbol = " "
format = '[$symbol]($style), '

[elixir]
symbol = " "
format = '[$symbol]($style), '

[erlang]
symbol = " "
format = '[$symbol]($style), '

[fennel]
symbol = " "
format = '[$symbol]($style), '

[fortran]
symbol = " "
format = '[$symbol]($style), '

[gleam]
symbol = " "
format = '[$symbol]($style), '

[golang]
symbol = "󰟓 "
format = '[$symbol]($style), '

[gradle]
symbol = " "
format = '[$symbol]($style), '

[haskell]
symbol = " "
format = '[$symbol]($style), '

[java]
symbol = " "
format = '[$symbol]($style), '

[julia]
symbol = " "
format = '[$symbol]($style), '

[kotlin]
symbol = " "
format = '[$symbol]($style), '

[lua]
symbol = " "
format = '[$symbol]($style), '

[meson]
symbol = "󰔷 "
format = '[$symbol]($style), '

[mojo]
symbol = "󰈸 "
format = '[$symbol]($style), '

[nodejs]
symbol = " "
format = '[$symbol]($style), '

[ocaml]
symbol = " "
format = '[$symbol]($style), '

[odin]
symbol = "󰟢 "
format = '[$symbol]($style), '

[perl]
symbol = " "
format = '[$symbol]($style), '

[php]
symbol = " "
format = '[$symbol]($style), '

[python]
symbol = " "
format = '[$symbol]($style), '

[ruby]
symbol = " "
format = '[$symbol]($style), '

[rust]
symbol = "󱘗 "
format = '[$symbol]($style), '

[scala]
symbol = " "
format = '[$symbol]($style), '

[swift]
symbol = " "
format = '[$symbol]($style), '

[zig]
symbol = " "
format = '[$symbol]($style), '
