"$schema" = 'https://starship.rs/config-schema.json'

# A minimal left prompt
right_format = """
{\
$c\
$cpp\
$dart\
$fortran\
$gleam\
$golang\
$haskell\
$java\
$julia\
$kotlin\
$lua\
$nodejs\
$ocaml\
$odin\
$perl\
$php\
$python\
$ruby\
$rust\
$scala\
$swift\
$zig\
$nix_shell\
$git_status\
$git_state\
$git_commit\
$git_branch\
$time\
}\
"""

# move the rest of the prompt to the right
format = """
$username\
$sudo\
$hostname\
$directory
[}](bold purple) 
"""

[character]
success_symbol = "[}](magenta)"
error_symbol = "[}](orange)"

[cmd_duration]
disabled = true

[time]
format = '[$time]($style)'
time_format = ", %R"
disabled = false

[direnv]
symbol = " "

[directory]
read_only = " 󰌾"
format = ', [$path]($style)[$read_only]($read_only_style)}:'

[git_branch]
symbol = " "
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_commit]
tag_symbol = '  '
format = '[\($hash$tag\)]($style), '

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\), '

[git_status]
format = '([$all_status$ahead_behind](bold), )'
renamed = '[R](blue)'
deleted = '[D](red)'
modified = '[*](yellow)'
stashed = '[\$](orange)'
ahead = ', [](yellow)'
behind = ', [](orange)'
conflicted = ', [](red)'
diverged = ', [](magenta)'
untracked = '[+](green)'

[hostname]
format = '[$hostname](blue)'

[nix_shell]
symbol = " "
format = '[$symbol]($style), '
pure_msg = ''
impure_msg = ''

[sudo]
symbol = " "
format = ':[$symbol]($style)'

[username]
format = '{[$user]($style)@'

[bun]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[c]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[cpp]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[cmake]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[crystal]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[dart]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[deno]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[elixir]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[erlang]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[fennel]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[fortran]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[gleam]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[golang]
symbol = "󰟓 "
format = '[$symbol($major.$minor)]($style)'

[gradle]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[haskell]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[java]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[julia]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[kotlin]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[lua]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[meson]
symbol = "󰔷 "
format = '[$symbol($major.$minor)]($style)'

[mojo]
symbol = "󰈸 "
format = '[$symbol($major.$minor)]($style)'

[nodejs]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[ocaml]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[odin]
symbol = "󰟢 "
format = '[$symbol($major.$minor)]($style)'

[perl]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[php]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[python]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[ruby]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[rust]
symbol = "󱘗 "
format = '[$symbol($major.$minor)]($style)'

[scala]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[swift]
symbol = " "
format = '[$symbol($major.$minor)]($style)'

[zig]
symbol = " "
format = '[$symbol($major.$minor)]($style)'
